### ISSUE TITLE
Playwright post install process with > 7.0.*

### ISSUE THREAD

**Issue by mdp** [robocorp/rpaframework#111]
I'm following the docs with regards to RCC.

The following conda.yaml file is given as an example:

```yaml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.5
  - pip=20.1
  - nodejs=14.2.0
  - pip:
    - rpaframework==6.7.1
    - robotframework-browser==2.3.3
rccPostInstall:
  - rfbrowser init
```

However with v7.0 including Playwright, I had assumed the following would work:

```yaml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.5
  - pip=20.1
  - nodejs=14.2.0
  - pip:
    - rpaframework==7.0.*
rccPostInstall:
  - rfbrowser init
```

However this throws an error because it can't find 'rfbrowser`

```
===  new live  ---  post install phase ===
Running post install script 'rfbrowser init' ...
Script 'rfbrowser init' failure: Cannot find command: rfbrowser
```

I'm able to work around this by installing 'robotframework-browser' but then I'm still able to use RPA.Browser.Playwright.

```yaml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.5
  - pip=20.1
  - nodejs=14.2.0
  - pip:
    - rpaframework==7.0.*
    - robotframework-browser==2.3.*
rccPostInstall:
  - rfbrowser init
```

What's the preferred strategy to use v7 and the playwright post install process?

Thanks
