### ISSUE TITLE
`RPA.Tables`: Not getting the first column values from csv

### ISSUE THREAD

**Issue by BuilesYeison** [robocorp/rpaframework#1156]
Hi!

I am trying to get csv data using `read_table_from_csv` method from `RPA.Tables`, but, im getting the first column values as _None_. I checkout the column name and its not wrong, also i have added `header` parameter into the method and also i have changed the delimiters from ';' to ','.

Note: i am getting succesfully the other column values.

Code: 
``` Python
from RPA.Tables import Tables
tables = Tables()

CONFIG_PATH = "output/config.csv"
CONFIG_STATUS_KEY ="status"
CONFIG_TENANT_KEY = "tenant_name"
CONFIG_PATH_KEY = "path"

config_data = tables.read_table_from_csv(
            CONFIG_PATH, columns=[CONFIG_TENANT_KEY,CONFIG_STATUS_KEY,CONFIG_PATH_KEY], header=True
)
```
This is my `config.csv` file:
``` CSV
tenant_name,status,path
tenant1,active,C:\Users\{0}\Desktop\dev\PruebaConceptoRPA
tenant2,inactive,C:\Users\{0}\Desktop\dev\PruebaConceptoRPA
```
This is my `conda.yaml` file:
``` yaml
dependencies:
  - python=3.10.12                # https://pyreadiness.org/3.10
  - pip=23.2.1                    # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip:
    - rpaframework==28.0.0        # https://rpaframework.org/releasenotes.html
    - robocorp==1.4.0             # https://pypi.org/project/robocorp
    - robocorp-browser==2.2.1     # https://pypi.org/project/robocorp-browser
```

When i debug and explore the value, i see this:
![image](https://github.com/robocorp/rpaframework/assets/54378260/9b342138-91af-4d96-b707-ac50a4ab122d)

I think this is a bug, thank you for your time!
