### ISSUE TITLE
RPA.Browser.Selenium.Attach Chrome Browser does not attach if there is another Chrome instance open

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/rpaframework#130]
Library: `RPA.Browser.Selenium`

Keyword: `Attach Chrome Browser` 

The attach does not work if there is another Chrome instance open before opening one from the command-prompt or the terminal. Works if all instances are first shut down, and the debug-one is then opened with `start chrome.exe -remote-debugging-port=9222`.

Assumed the robot attaches to the instance that has the debug port open.

The error message:

```
WebDriverException: Message: unknown error: cannot connect to chrome at localhost:9222
from chrome not reachable
```

Test robot:

```robot
*** Settings ***
Library           RPA.Browser.Selenium

*** Tasks ***
Attach to Chrome
    Attach Chrome Browser    9222
    Go To    https://www.google.com/?hl=en
    Input Text    name:q    Dinosaur
    Press Keys    name:q    ENTER
```

`conda.yaml`:

```yaml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.5
  - pip=20.1
  - pip:
      - rpaframework==7.2.0
```
