### ISSUE TITLE
RPA.PDF.Add Files To Pdf keyword not found when adding rpaframework as a conda dependency

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/rpaframework#178]
`RPA.PDF.Add Files To Pdf` keyword not found when adding `rpaframework` as a conda dependency. Works with `pip`:

```yaml
channels:
  - conda-forge

dependencies:
  - python=3.7.5
  - rpaframework=9.6.0
```
