### ISSUE TITLE
Update Playwright example conda.yaml

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/rpaframework#187]
The current Playwright example `conda.yaml` contains old dependencies and conda channels that can cause issues when users experiment with the libraries:

https://rpaframework.org/libraries/browser_playwright/index.html

Also, maybe better to import `rpaframework` after `robotframework-browser` to get a better chance of getting the `robotframework` version that Robocorp stack prefers.

Here's a suggestion for an updated example:

```yaml
channels:
  - conda-forge

dependencies:
  - python=3.7.5
  - pip=20.1
  - nodejs=14.15.4
  - pip:
      - robotframework-browser==5.0.1
      - rpaframework==10.2.0
rccPostInstall:
  - rfbrowser init
```
