### ISSUE TITLE
Support Robot6

### ISSUE THREAD

**Issue by pianofab** [robocorp/rpaframework#673]
The dependencies specified by this project prevent installation alongside the just released Robot 6 and also Python 3.10.
Issuing `conda install rpaframework>=18.0.0` yields

Your python: python=3.10

**Comment by mikahanninen** [comment]
Hi @pianofab. The Robot Framework 6 was released this week and we don't include new Robot Framework major releases this fast in our tools, because of the potential fixes it might require.

What is your need for Robot Framework 6 ?

And Python 3.10 should be working just fine, for example, this one worked for me.

```yaml
# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  # Define conda-forge packages here -> https://anaconda.org/search
  # When available, prefer the conda-forge packages over pip as installations are more efficient.
  - python=3.10.6               # https://pyreadiness.org/3.10/ 
  - pip=22.1.2                  # https://pip.pypa.io/en/stable/news/
  - pip:
      # Define pip packages here -> https://pypi.org/
      - rpaframework==18.0.0    # https://rpaframework.org/releasenotes.html
```
