### ISSUE TITLE
Install conflict exchangelib, requests[socks]==2.28.1 and rpaframework

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#755]
I am trying to install some new version of rpaframework.
Whatever recent version I use I keep on ending in this error:
ERROR: Cannot install exchangelib, requests[socks]==2.28.1 and rpaframework because these package versions have conflicting dependencies.

The conflict is caused by:
    exchangelib 4.9.0 depends on requests>=2.7
    notifiers 1.3.3 depends on requests<3.0.0 and >=2.27.1
    o365 2.0.24 depends on requests>=2.18.0
    requests-oauthlib 1.3.1 depends on requests>=2.0.0
    robotframework-requests 0.9.4 depends on requests
    simple-salesforce 1.12.2 depends on requests>=2.22.0
    requests-ntlm 1.1.0 depends on requests>=2.0.0
    requests[socks] 2.28.1 depends on requests 2.28.1 (Installed)

As far as I analyze the conflict the version of requests seems to be OK. Is exchangelib doing something wrong? Exchangelib belongs to rpaframework set up or not?

**Comment by cmin764** [comment]
I just checked this _conda.yaml_ with a robot run (or `rcc task shell` for a quick run):
```yaml
channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13

  - pip=22.1.2
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==19.4.2 # https://rpaframework.org/releasenotes.html
      - requests[socks]==2.28.1
```

And it built my env fast and without any issues.

Used this env with the Portal [example](https://robocorp.com/portal/robot/robocorp/example-oauth-email) here and managed to run the but successfully as well. So maybe you should upgrade your library to the latest **19.x.x** version.

```
bash-3.2$ pip freeze | grep -i requests
requests==2.28.1
requests-file==1.5.1
requests-ntlm==1.1.0
requests-oauthlib==1.3.1
requests-toolbelt==0.10.1
robotframework-requests==0.9.4
bash-3.2$ pip freeze | grep -i exchangelib
exchangelib==4.9.0
bash-3.2$ pip freeze | grep -i rpa
rpaframework==19.4.2
rpaframework-core==10.0.4
rpaframework-dialogs==4.0.0
rpaframework-pdf==5.0.0
```
